// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AuditLogs struct {
	ID           int64 `json:"id"`
	UserID       int64 `json:"user_id"`
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
	StoreID      int64 `json:"store_id"`
	// data sebelum diubah
	OldData pqtype.NullRawMessage `json:"old_data"`
	// data sesudah diubah
	NewData pqtype.NullRawMessage `json:"new_data"`
	Title   sql.NullString        `json:"title"`
	// bahasa manusia
	Description sql.NullString `json:"description"`
	// LOGIN, LOGOUT, CREATE, UPDATE, DELETE, PAYMENT, EXPORT.
	Action sql.NullString `json:"action"`
	// IPv4/IPv6
	IpAddress sql.NullString `json:"ip_address"`
	// device/browser
	UserAccessFrom sql.NullString `json:"user_access_from"`
	// SUCCESS, FAILED.
	Status    sql.NullString `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type Auths struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Carts struct {
	// orderan yang sudah dipesan namun belum di bayar
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// required kalo customer
	StoreID int64 `json:"store_id"`
	// required kalo customer
	TableID int64 `json:"table_id"`
	// jumlah quantity x price
	TotalCost sql.NullInt64 `json:"total_cost"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type CartsItems struct {
	ID       int64 `json:"id"`
	CartID   int64 `json:"cart_id"`
	ItemID   int64 `json:"item_id"`
	Quantity int64 `json:"quantity"`
	// snapshot harga saat order
	Price int64 `json:"price"`
}

type Items struct {
	ID     int64  `json:"id"`
	MenuID int64  `json:"menu_id"`
	Name   string `json:"name"`
	Price  int64  `json:"price"`
	// snack , makanan , minuman
	Category sql.NullString `json:"category"`
	// stock ada = true , stock kosong = false
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Menus struct {
	ID        int64     `json:"id"`
	StoreID   int64     `json:"store_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Orders struct {
	// orderan yang sudah di bayar
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	PaymentID int64 `json:"payment_id"`
	StoreID   int64 `json:"store_id"`
	// in_procces (lagi dibuat),canceled (makanan di batalkan), done (sudah di antar ke meja), (status pesanan)
	Status    sql.NullString `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Payments struct {
	ID     int64 `json:"id"`
	CartID int64 `json:"cart_id"`
	// bayar dengan qr_midtrans atau di cashier
	Method string `json:"method"`
	// order id (midtrans)
	MidtransID sql.NullString `json:"midtrans_id"`
	// gross amount (midtrans) ambil dari total cost di carts
	GrossAmount string `json:"gross_amount"`
	// payment_type (midtrans)
	PaymentMethod sql.NullString `json:"payment_method"`
	// jenis bank
	Bank sql.NullString `json:"bank"`
	// untuk struk
	PaymentReceipt sql.NullString `json:"payment_receipt"`
	// pending, success, failed (status pembayaran)
	Status sql.NullString `json:"status"`
	// untuk struk
	Invoice      sql.NullString        `json:"invoice"`
	MidtransData pqtype.NullRawMessage `json:"midtrans_data"`
	PaidAt       time.Time             `json:"paid_at"`
}

type Permissions struct {
	ID int64 `json:"id"`
	// (e.g. "create_order", "manage_users", "view_reports", "change_table_number")
	Name string `json:"name"`
}

type Roles struct {
	ID int64 `json:"id"`
	// e.g Super Admin , owner, cashier, customer
	RoleName string `json:"role_name"`
}

type RolesPermissions struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type StoreTables struct {
	ID          int64     `json:"id"`
	StoreID     int64     `json:"store_id"`
	TableNumber string    `json:"table_number"`
	QrCode      string    `json:"qr_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Stores struct {
	ID int64 `json:"id"`
	// 0 no access , 1 menu qr
	StoreAccessID int64 `json:"store_access_id"`
	// nama toko
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StoresAccess struct {
	ID int64 `json:"id"`
	// meja_qr , kasir management / untuk access menu apa saja yang bisa di pakai
	Name string `json:"name"`
}

type Transactions struct {
	// catatan untuk database toko berapa pemasukan yang berhasil di proses , kalau status order di cancel maka hapus dari transactions
	ID      int64 `json:"id"`
	StoreID int64 `json:"store_id"`
	OrderID int64 `json:"order_id"`
	Income  int64 `json:"income"`
	// ambil dari order id --> cart id --> cart_items apa aja
	Detail    pqtype.NullRawMessage `json:"detail"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type Users struct {
	ID int64 `json:"id"`
	// // 0 / 1 / 2 / 3 / 4
	RoleID      int64          `json:"role_id"`
	Email       sql.NullString `json:"email"`
	PhoneNumber string         `json:"phone_number"`
	// nama orang
	Name string `json:"name"`
	// account status
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type UsersStores struct {
	UserID  int64 `json:"user_id"`
	StoreID int64 `json:"store_id"`
}
