// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store_access.sql

package db

import (
	"context"
)

const createStoreAccess = `-- name: CreateStoreAccess :one
INSERT INTO stores_access (
  name
) VALUES (
  $1
)
RETURNING id, name
`

func (q *Queries) CreateStoreAccess(ctx context.Context, name string) (StoresAccess, error) {
	row := q.db.QueryRowContext(ctx, createStoreAccess, name)
	var i StoresAccess
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getStoreAccess = `-- name: GetStoreAccess :one
SELECT id, name FROM stores_access
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStoreAccess(ctx context.Context, id int64) (StoresAccess, error) {
	row := q.db.QueryRowContext(ctx, getStoreAccess, id)
	var i StoresAccess
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
